import { useState, useEffect } from 'react';
import { Lightbulb, RefreshCw, Zap, Clock, CheckSquare } from 'lucide-react';

interface Recommendation {
  title: string;
  description: string;
  impact: 'High' | 'Medium' | 'Low';
  effort: 'High' | 'Medium' | 'Low';
  actionSteps: string[];
}

interface RecommendationsProps {
  apiKey: string;
  grokApiKey: string;
  activeEngine: 'gemini' | 'grok';
  datasetLength: number;
}

export const Recommendations: React.FC<RecommendationsProps> = ({ 
  apiKey, 
  grokApiKey,
  activeEngine,
  datasetLength 
}) => {
  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const fetchRecommendations = async () => {
    if (datasetLength === 0) return;
    setLoading(true);
    setErrorMsg('');
    try {
      const res = await fetch(`/api/recommendations?engine=${activeEngine}`, {
        headers: {
          'x-gemini-key': apiKey,
          'x-grok-key': grokApiKey
        }
      });
      if (!res.ok) {
        const errJson = await res.json().catch(() => ({ error: res.statusText }));
        throw new Error(errJson.error || `HTTP ${res.status}`);
      }
      const results = await res.json();
      setRecs(results);
    } catch (e: any) {
      setErrorMsg(e.message || 'Failed to generate recommendations.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, [datasetLength, activeEngine]);

  const getImpactColor = (val: string) => {
    if (val === 'High') return { bg: 'rgba(16, 185, 129, 0.15)', text: 'var(--primary)', border: 'rgba(16, 185, 129, 0.3)' };
    if (val === 'Medium') return { bg: 'rgba(245, 158, 11, 0.15)', text: 'var(--warning)', border: 'rgba(245, 158, 11, 0.3)' };
    return { bg: 'rgba(156, 163, 175, 0.15)', text: 'var(--text-muted)', border: 'rgba(156, 163, 175, 0.3)' };
  };

  const getEffortColor = (val: string) => {
    if (val === 'Low') return { bg: 'rgba(16, 185, 129, 0.15)', text: 'var(--primary)', border: 'rgba(16, 185, 129, 0.3)' };
    if (val === 'Medium') return { bg: 'rgba(245, 158, 11, 0.15)', text: 'var(--warning)', border: 'rgba(245, 158, 11, 0.3)' };
    return { bg: 'rgba(239, 68, 68, 0.15)', text: 'var(--error)', border: 'rgba(239, 68, 68, 0.3)' };
  };

  if (datasetLength === 0) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '60vh', color: 'var(--text-muted)' }}>
        <Lightbulb size={48} style={{ marginBottom: '1rem', opacity: 0.3 }} />
        <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: '1.25rem' }}>No Data for Recommendations</h3>
        <p style={{ marginTop: '0.5rem', textAlign: 'center', fontSize: '0.9rem' }}>Please upload your data in the **Upload Data** tab to unlock automated strategic recommendations.</p>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.6rem' }}>Strategic AI Recommendations ({activeEngine.toUpperCase()})</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginTop: '0.25rem' }}>
            Actionable optimization steps generated by analyzing dataset dimensions and financial metrics.
          </p>
        </div>
        <button className="button" onClick={fetchRecommendations} disabled={loading}>
          <RefreshCw className={loading ? 'animate-spin' : ''} size={16} />
          {loading ? 'Analyzing Data...' : 'Regenerate Insights'}
        </button>
      </div>

      {errorMsg && (
        <div style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', borderRadius: '8px', padding: '0.85rem 1rem', color: '#f87171', fontSize: '0.85rem', display: 'flex', alignItems: 'flex-start', gap: '0.5rem' }}>
          <span style={{ fontWeight: 700, flexShrink: 0 }}>⚠ Error:</span>
          <span>{errorMsg}</span>
        </div>
      )}

      {loading ? (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '40vh', gap: '1rem' }}>
          <RefreshCw className="animate-spin" size={36} style={{ color: 'var(--primary)' }} />
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Running strategic classification algorithms via {activeEngine.toUpperCase()} model...</p>
        </div>
      ) : (
        <div className="recommendations-grid">
          {recs.map((rec, i) => {
            const impCol = getImpactColor(rec.impact);
            const effCol = getEffortColor(rec.effort);

            return (
              <div key={i} className="glass-panel rec-card">
                <div>
                  <div className="rec-header">
                    <h3 className="rec-title">{rec.title}</h3>
                    <div style={{ background: 'rgba(255, 255, 255, 0.03)', padding: '0.4rem', borderRadius: '50%', color: 'var(--primary)' }}>
                      <Lightbulb size={18} />
                    </div>
                  </div>

                  <div className="badge-row">
                    <span 
                      className="badge" 
                      style={{ backgroundColor: impCol.bg, color: impCol.text, borderColor: impCol.border, border: '1px solid', textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: '0.25rem' }}
                    >
                      <Zap size={10} /> Impact: {rec.impact}
                    </span>
                    <span 
                      className="badge" 
                      style={{ backgroundColor: effCol.bg, color: effCol.text, borderColor: effCol.border, border: '1px solid', textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: '0.25rem' }}
                    >
                      <Clock size={10} /> Effort: {rec.effort}
                    </span>
                  </div>

                  <p className="rec-desc" style={{ marginTop: '1.25rem' }}>{rec.description}</p>
                </div>

                <div className="rec-steps">
                  <h4 className="rec-steps-title">
                    <CheckSquare size={12} style={{ display: 'inline', marginRight: '0.25rem', verticalAlign: 'text-bottom' }} /> Suggested Action Plan
                  </h4>
                  <ul className="rec-steps-list">
                    {rec.actionSteps.map((step, idx) => (
                      <li key={idx}>{step}</li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
